/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedLeaseAgreeRouteImport } from './routes/_authenticated/lease-agree'
import { Route as AuthenticatedMyRentalRouteImport } from './routes/_authenticated/my-rental'
import { Route as AuthenticatedSavedRentalRouteImport } from './routes/_authenticated/saved-rental'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSuppInqRouteImport } from './routes/_authenticated/supp-inq'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaseAgreeRoute = AuthenticatedLeaseAgreeRouteImport.update({
  id: '/lease-agree',
  path: '/lease-agree',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyRentalRoute = AuthenticatedMyRentalRouteImport.update({
  id: '/my-rental',
  path: '/my-rental',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSavedRentalRoute =
  AuthenticatedSavedRentalRouteImport.update({
    id: '/saved-rental',
    path: '/saved-rental',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppInqRoute = AuthenticatedSuppInqRouteImport.update({
  id: '/supp-inq',
  path: '/supp-inq',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/lease-agree': typeof AuthenticatedLeaseAgreeRoute
  '/my-rental': typeof AuthenticatedMyRentalRoute
  '/saved-rental': typeof AuthenticatedSavedRentalRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supp-inq': typeof AuthenticatedSuppInqRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/lease-agree': typeof AuthenticatedLeaseAgreeRoute
  '/my-rental': typeof AuthenticatedMyRentalRoute
  '/saved-rental': typeof AuthenticatedSavedRentalRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/supp-inq': typeof AuthenticatedSuppInqRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/lease-agree': typeof AuthenticatedLeaseAgreeRoute
  '/_authenticated/my-rental': typeof AuthenticatedMyRentalRoute
  '/_authenticated/saved-rental': typeof AuthenticatedSavedRentalRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/supp-inq': typeof AuthenticatedSuppInqRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/lease-agree'
    | '/my-rental'
    | '/saved-rental'
    | '/settings'
    | '/supp-inq'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/lease-agree'
    | '/my-rental'
    | '/saved-rental'
    | '/settings'
    | '/supp-inq'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/lease-agree'
    | '/_authenticated/my-rental'
    | '/_authenticated/saved-rental'
    | '/_authenticated/settings'
    | '/_authenticated/supp-inq'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lease-agree': {
      id: '/_authenticated/lease-agree'
      path: '/lease-agree'
      fullPath: '/lease-agree'
      preLoaderRoute: typeof AuthenticatedLeaseAgreeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-rental': {
      id: '/_authenticated/my-rental'
      path: '/my-rental'
      fullPath: '/my-rental'
      preLoaderRoute: typeof AuthenticatedMyRentalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saved-rental': {
      id: '/_authenticated/saved-rental'
      path: '/saved-rental'
      fullPath: '/saved-rental'
      preLoaderRoute: typeof AuthenticatedSavedRentalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supp-inq': {
      id: '/_authenticated/supp-inq'
      path: '/supp-inq'
      fullPath: '/supp-inq'
      preLoaderRoute: typeof AuthenticatedSuppInqRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedLeaseAgreeRoute: typeof AuthenticatedLeaseAgreeRoute
  AuthenticatedMyRentalRoute: typeof AuthenticatedMyRentalRoute
  AuthenticatedSavedRentalRoute: typeof AuthenticatedSavedRentalRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppInqRoute: typeof AuthenticatedSuppInqRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLeaseAgreeRoute: AuthenticatedLeaseAgreeRoute,
  AuthenticatedMyRentalRoute: AuthenticatedMyRentalRoute,
  AuthenticatedSavedRentalRoute: AuthenticatedSavedRentalRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppInqRoute: AuthenticatedSuppInqRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
